version: '3.4'

services:
  lojaservicos.api.autor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6104:80"

  lojaservicos.api.livro:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6105:80"


  lojaservicos.api.carrinhocompras:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

