version: '3.4'

services:
  lojaservicos.api.autor:
    image: ${DOCKER_REGISTRY-}lojaservicosapiautor
    build:
      context: .
      dockerfile: LojaServicos.Api.Autor/Dockerfile
  lojaservicos.api.livro:
    image: ${DOCKER_REGISTRY-}lojaservicosapilivro
    build:
      context: .
      dockerfile: LojaServicos.Api.Livro/Dockerfile

  lojaservicos.api.carrinhocompras:
    image: ${DOCKER_REGISTRY-}lojaservicosapicarrinhocompras
    build:
      context: .
      dockerfile: LojaServicos.Api.CarrinhoCompras/Dockerfile

networks:
  default:
    external:
       name: microservicenet

