version: '3.4'

services:
  lojaservicos.api.autor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6104:80"

  lojaservicos.api.livro:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6105:80"


  lojaservicos.api.carrinhocompras:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Livros=http://lojaservicos.api.livro
    ports:
      - "6106:80"

  lojaservicos.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - lojaservicos.api.livro
    ports:
      - "6107:80"

